### ISSUE TITLE
List initial chunks per entry point in side menu

### ISSUE THREAD

**Issue by karlvr** [webpack-contrib/webpack-bundle-analyzer#456] opened 2021-07-15 11:44 UTC
#### Issue description
I'd like to be able to specifically identify initial chunks.

Please let me know if I've missed anything obvious, or if my thinking is flawed, or any improvements or suggestions. If it sounds like a good idea I'd be happy to look into contributing this to the project.

**Comment by valscion** [comment] 2021-07-15 14:12
Hi, thanks for opening an issue!

I think there was something related to this idea in previous issues. Do you want to try searching for any remotely related issues in case we've discussed an aspect of this earlier? I only have a vague memory at this point, so I could be wrong, too.

**Comment by karlvr** [comment] 2021-07-15 20:02
Thanks @valscion I wonder if it's #296. My suggestion is a lot simpler; just identify which chunks are part of entry points so you know which chunks are loaded on page load. 

I love the idea in #296 of a hierarchy of dependencies, but it seems a little tangential to the project.

**Comment by karlvr** [comment] 2021-07-15 20:05
No I think it's #289. I imagined another heading "entry points" with a list of names and sizes, and ticking one would tick the corresponding chunks.

**Comment by valscion** [comment] 2021-07-16 07:38
Yeah looks like #289 is quite identical to this feature request indeed. Do you mind if we close this issue as a duplicate of the same request so we can keep track of which features have been requested?

**Closed** 2021-07-18 21:36 UTC
Labels: Type: Discussion, type: Feature
