### ISSUE TITLE
 Can I get the size of the package displayed in the open html after calculation?

### ISSUE THREAD

**Issue by ShiChenCong** [webpack-contrib/webpack-bundle-analyzer#268] opened 2019-04-16 09:11 UTC
#### Issue description

Can I get the size of the package displayed in the open html after calculation?

**Comment by ShiChenCong** [comment] 2019-04-16 09:12
I tried to get the data in stats.json, but this is not calculated.

**Comment by valscion** [comment] 2019-04-16 10:21
Is this a duplicate of #194?

**Closed** 2019-04-17 07:30 UTC
Labels: status: Needs triage
