### ISSUE TITLE
Worker doesn't exist in output stats

### ISSUE THREAD

**Issue by romanlex** [webpack-contrib/webpack-bundle-analyzer#193] opened 2018-06-29 11:30 UTC
Hello.
I create this issues https://github.com/webpack-contrib/worker-loader/issues/155 in worker-loader repo because when I'm build app I don't see any workers file in stats(

**Comment by valscion** [comment] 2018-06-29 11:38
Hi there! :relaxed:

This seems to be duplicate of #150. If you'd like to help, setting up a minimal example project with `worker-loader` + `webpack-bundle-analyzer` as asked in #150 would be helpful.

Feel free to continue discussion in #150. I'll close this as a duplicate now.

**Closed by valscion** 2018-06-29 11:38 UTC
