### ISSUE TITLE
Add support for reading from STDIN rather than a file

### ISSUE THREAD

**Issue by dancrumb** [webpack-contrib/webpack-bundle-analyzer#167] opened 2018-04-11 16:55 UTC
#### Issue description
The pattern:

```
webpack --profile --json > stats.json
webpack-bundle-analyzer bundle/output/path/stats.json
```

is a little un-*nix.

What would be nicer would be something like

```
webpack --profile --json | webpack-bundle-analyzer -
```

When I have some time, I'd be happy to create a PR for this.

**Comment by valscion** [comment] 2018-04-12 07:01
Hi there! Thanks for the feature suggestion ☺️ 

The problem is that we also need the bundled contents from the filesystem. Otherwise we'd only be able to visualize the stat size, which isn't really satisfying.

Thank you for offering to create this kind of PR, but I think it might be out of scope of this library. What do you think, @th0r?

**Comment by th0r** [comment] 2018-04-12 08:48
Well, I won't mind a PR introducing this feature but with a note in the docs that "in this case you won't see parsed and gzipped sizes".

**Comment by antialias** [comment] 2020-04-16 16:38
@dancrumb You can use the `<()` operator right now if your shell supports it:

```sh
webpack-bundle-analyzer <(webpack --profile --json)
```
It's not completely satisfying (as predicted by @th0r and @valscion). Here is the message:

```txt
Error parsing bundle asset "/dev/fd/main.cc2aacef761dbe6fd147.bundle.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.
```

<img width="520" alt="Screen Shot 2020-04-16 at 9 37 33 AM" src="https://user-images.githubusercontent.com/447517/79482624-ef66d480-7fc5-11ea-8bc3-39248764e739.png">

**Comment by dancrumb** [comment] 2022-12-07 00:53
Probably time to close this, right?

**Comment by valscion** [comment] 2022-12-07 07:27
Yeah you can close this if you feel like it 😌 we still don't support reading from STDIN but we're not doing this feature ourselves, either.

**Closed** 2022-12-07 13:30 UTC
Labels: Status: Ready for PR, type: Feature
