### ISSUE TITLE
webpack-bundle-analyzer can't parse bundle built with output.libraryTarget == 'this'

### ISSUE THREAD

**Issue by secondfry** [webpack-contrib/webpack-bundle-analyzer#436] opened 2021-04-17 13:17 UTC
#### Issue description
webpack-bundle-analyzer can't parse bundles built with `output.libraryTarget: this` (and `output.library` to its library name).

#### Technical info
<pre>
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 393.32 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 7.9.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /Users/secondfry/.brew/bin/watchman
  npmPackages:
    fork-ts-checker-webpack-plugin: ^6.2.1 => 6.2.1
    tsconfig-paths-webpack-plugin: ^3.5.1 => 3.5.1
    webpack: ^4.46.0 => 4.46.0
    webpack-bundle-analyzer: ^4.4.0 => 4.4.0
    webpack-cli: ^4.6.0 => 4.6.0
</pre>

#### Debug info
Module is being used as plugin.
Plugin was provided no options.
Other plugins:
```
tsconfig-paths-webpack-plugin
mini-css-extract-plugin
```

`stats.json` file created with following options:
```js
new BundleAnalyzerPlugin({
  analyzerMode: 'disabled',
  generateStatsFile: true,
  // Excludes module sources from stats file so there won't be any sensitive data
  statsOptions: { source: false }
})
```
[stats.json.txt](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/6329288/stats.json.txt)
[webpack.config.ts.txt](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/6329289/webpack.config.ts.txt)

**Comment by secondfry** [comment] 2021-04-17 13:21
Seems to be duplicate of #372, didn't find it before submitting...

**Comment by valscion** [comment] 2021-04-19 06:34
Ok, closing as a duplicate of #372.

**Closed by valscion** 2021-04-19 06:34 UTC
