### ISSUE TITLE
Node modules shown only for `stats` view.

### ISSUE THREAD

**Issue by Arturszott** [webpack-contrib/webpack-bundle-analyzer#171] opened 2018-05-08 14:24 UTC
#### Issue description
Node_modules are shown only for `stats` view, but not in `parsed` and `gzip`

**Stats:**
<img width="516" alt="screen shot 2018-05-08 at 15 52 39" src="https://user-images.githubusercontent.com/2734152/39762140-2db82f06-52da-11e8-8117-41fa65d6eabe.png">

**Parsed:**
<img width="466" alt="screen shot 2018-05-08 at 15 52 32" src="https://user-images.githubusercontent.com/2734152/39762150-36f8c5bc-52da-11e8-8b6b-16b73323adc7.png">

#### Technical info
* Webpack Bundle Analyzer version: 2.11.1
* Webpack version: 4.5.0
* Node.js version: 8.9.4
* npm/yarn version: 5.6.0
* OS: osx

#### Debug info
Using as CLI

`NODE_ENV=production webpack --bail --profile --json > ./build/stats.json`

What other Webpack plugins were used?

MiniCssExtractPlugin, SaveAssetsJson,  CopyAssets, ManifestPlugin, StatsPlugin

With webpack 3.X everything was fine.

[stats.json.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/1987338/stats.json.zip)

**Comment by th0r** [comment] 2018-05-08 19:52
Could you provide `stats.json` and resulting bundles?

**Comment by Arturszott** [comment] 2018-05-09 10:14
@th0r done

**Comment by th0r** [comment] 2018-05-09 14:02
> and resulting bundles

I didn't find resulting bundles in the archive. Unfortunately stats file alone won't help here because your `stats` sizes are valid - the issue is with `parsed` sizes.
If you don't want to publish your bundles here you can send them to me via email.

**Comment by iwaszko** [comment] 2018-05-12 00:16
The same happens for me. Please find a sample project, stats.json and bundles in the .zip attached: [demo.zip](https://github.com/webpack-contrib/webpack-bundle-analyzer/files/1997126/demo.zip).

The issue seems to be caused by the first import in `index.scss` file. Commenting it out restores the correct behaviour.

Also, switching to 'Stat' and then 'Parsed' shows `node_modules` for me, although I believe sizes of packages on the graph are not correct then.

**Comment by th0r** [comment] 2018-05-13 12:17
@iwaszko should be fixed in `v2.11.3`
@Arturszott could't you try `v2.11.3` and see if the problem has disappeared?

**Comment by iwaszko** [comment] 2018-05-13 23:18
`2.11.3` works great for me. Thanks!

**Comment by Arturszott** [comment] 2018-05-14 06:45
@th0r Like a charm! Thanks! I love this tool!

**Closed** 2018-05-14 06:45 UTC
Labels: status: Needs triage

**Comment by cdauth** [comment] 2021-02-27 15:55
It looks like I'm seeing this exact behaviour with webpack-bundle-analyzer 4.3.0 and webpack 5.24.2.

**Comment by valscion** [comment] 2021-03-01 07:28
Please open a new issue and fill in all the required information in the issue description. Commenting on issues that have been closed for years will not help
