### ISSUE TITLE
Break down "+ x modules" for more information

### ISSUE THREAD

**Issue by flopes89** [webpack-contrib/webpack-bundle-analyzer#162] opened 2018-03-22 07:49 UTC
#### Issue description

What does the "+ x modules" description mean exactly? Given e.g. this analyzer output:

![4lxvw](https://user-images.githubusercontent.com/1453127/37757429-5146063e-2dad-11e8-8c10-ecc35782a96e.png)

What exactly does the huge "+ x modules"  mean? How can I analyze it / break it down further to see, whats inside?

#### Technical info
* Webpack Bundle Analyzer version: 2.11.1
* Webpack version: 3.8.0
* Node.js version: 8.9.0
* npm/yarn version: 5.5.1
* OS: Windows 7x64

#### Debug info
How do you use this module?

**plugin**

If plugin, what options were provided?

```
new BundleAnalyzerPlugin({
	analyzerMode: "static",
	reportFilename: "../bundle-analyzer.html",
	openAnalyzer: false,
}),
```

What other Webpack plugins were used?

```
"brotli-webpack-plugin": "0.4.1",
"chunk-manifest-webpack-plugin": "git+https://github.com/reactql/chunk-manifest-webpack-plugin.git",
"i18n-webpack-plugin": "1.0.0",
"copy-webpack-plugin": "4.1.1",
"extract-text-webpack-plugin": "3.0.1",
"html-webpack-plugin": "2.30.1",
"image-webpack-loader": "3.4.2",
"webpack-chunk-hash": "0.5.0",
"webpack-config": "7.5.0",
"webpack-dev-server": "2.9.2",
"webpack-manifest-plugin": "1.3.2",
"webpack-node-externals": "1.6.0",
```

**Comment by valscion** [comment] 2018-03-22 07:59
Hi! Thanks for the detailed issue description ☺️ 

This is a known issue, and in this case, a duplicate of #115. With webpack 4, we will get enough details to show an approximation of what is in these "+ x modules" — see #158 for the new feature :tada:

The new feature can be a bit misleading as it doesn't filter away tree-shaked modules. And for that case, we've got #161.

**Closed by valscion** 2018-03-22 07:59 UTC

**Comment by valscion** [comment] 2018-03-22 08:01
Oh, and you could get visibility into these opaque chunks by removing usage of `webpack.optimize.ModuleConcatenationPlugin` in your webpack code.

**Comment by flopes89** [comment] 2018-03-22 08:04
Thanks for the pointers! I will check them out and follow them :)
